name: Builds the solution with multiple .NET versions

on:
  push:

env:
  BUILD_FILTER: 'HelloWorldNuget/HelloWorldNuget.slnx'
  BUILD_CONFIG: 'Release'
  PACKAGES_DIR: 'NuGetPackages'
  ARTIFACT_NAME: 'CreatedPackages'

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x\n9.0.x\n8.0.x'

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ env.BUILD_FILTER }}

    - name: Build
      shell: bash
      run: dotnet build ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore
      
    - name: NuGet Pack
      shell: bash
      run: dotnet pack ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore -o ${{ env.PACKAGES_DIR }}
      
    - name: Upload packages as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./${{ env.PACKAGES_DIR }}/
        retention-days: 7
