name: Publish new package version on NuGet

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/publish_on_nuget.yml"
      - "HelloWorldNuget/**"
  workflow_dispatch:

env:
  BUILD_FILTER: 'HelloWorldNuget/HelloWorldNuget.sln'
  BUILD_CONFIG: 'Release'
  ENABLE_TESTS: 'false'

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ env.BUILD_FILTER }}

    - name: Build
      shell: bash
      run: dotnet build ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore
