name: Publish new package version on NuGet

on:
#  push:
#    branches: [ "main" ]
#    paths:
#      - ".github/workflows/publish_on_nuget.yml"
#      - "HelloWorldNuget/**"
  workflow_dispatch:

env:
  BUILD_FILTER: 'HelloWorldNuget/HelloWorldNuget.slnx'
  BUILD_CONFIG: 'Release'
  PACKAGES_DIR: 'NuGetPackages'
  ARTIFACT_NAME: 'CreatedPackages'

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ env.BUILD_FILTER }}

    - name: Build
      shell: bash
      run: dotnet build ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore
      
    - name: NuGet Pack
      shell: bash
      run: dotnet pack ${{ env.BUILD_FILTER }} --configuration ${{ env.BUILD_CONFIG }} --no-restore -o ${{ env.PACKAGES_DIR }}
      
    - name: Upload packages as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./${{ env.PACKAGES_DIR }}/
        retention-days: 7

  publish_nuget:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write

    steps:

    - name: Download packages artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./
        
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: NuGet push
      run: dotnet nuget push ./*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
